### ISSUE TITLE
Infer zero suppression from coordinates

### ISSUE THREAD

**Issue by mcous** [mcous/gerber-parser#15]
Lots of gerber/drill files don't specify zero suppression. In many cases, coordinate strings exist in the file with zeros at the end or beginning that could be used to reliably infer zero suppression. The mechanism could be similar to how gerber-parser currently caches instructions until it decides whether a file is a drill file or a gerber file.

**Comment by kasbah** [comment]
I guess this can be closed with the merge of #17?
